# Makefile produced by _mmakefile

CC = gcc
LDFLAGS = -L$(HOME)/COMP9021/lib -lp_io -lm
CFLAGS = -std=gnu99 -Wall -ggdb -I$(HOME)/COMP9021/include

sources = tower_and_2_glass_marbles.c

a.out : $(sources)
	$(CC) $(CFLAGS) $(LDFLAGS) $(sources)
